### ISSUE TITLE
Version 2: Use some framework for devlopment

### ISSUE THREAD

**Issue by mubaidr** [a-to-z/PGshoutBox#1]
@a-to-z You are doing good with the development. :+1: 

This issue is targeted to the next version.

We should use some framework like Phone-gap(Personally preferred)/Xamarine:
-gives more flexibility for developing applications with web access 
-Porting to all mobile platforms. This app will support Windows and IOS too, along-with Android. 

I can start working on this application, using resources/ui designs from current development, You can participate to version 2 with your experience (off-course after release of version1).

**Comment by a-to-z** [comment]
awesome. I need someone for UI. get started
